#!/bin/bash
#SBATCH -J para
#SBATCH -p g1_user
#SBATCH --nodes=1
##SBATCH --time=72:00:00 
#SBATCH --ntasks-per-node=56
#SBATCH --error=%J.err          ###err log###
#SBATCH --output=%J.out         ###out log###

unset I_MPI_PMI_LIBRARY
export I_MPI_JOB_RESPECT_PROCESS_PLACEMENT=0

source /es01/software/profile.d/intel2020.sh

mpirun -np $SLURM_NPROCS  ~/apps/vasp/6.2/TS-Sol/vasp_std

scontrol show job $SLURM_JOBID

